### ISSUE TITLE
Error: (NaN Calc world cframe)

### ISSUE THREAD

**Issue by arisethee** [CelnakRBLX/SmartBone-2#13]
Happens if you put a part collision under one of the test capes. In the following picture:
![image](https://github.com/CelnakRBLX/SmartBone-2/assets/57269161/71884e64-a97f-410d-9213-7609f57a0460)

**Comment by JakeyWasTaken** [comment]
I can't seem to reproduce this, could you share steps on how to?

**Comment by JakeyWasTaken** [comment]
Im going to close this issue as stale, I've been unable to reproduce and without further reproduction steps this is no longer worth keeping open.

**Comment by JakeyWasTaken** [comment]
I think I know what caused this, fixed and shouldn't happen again.
