### ISSUE TITLE
If you see this report this as a bug, (NaN Calc world cframe) (x4999)

### ISSUE THREAD

**Issue by LogicalLion** [CelnakRBLX/SmartBone-2#22]
I have no idea how to replicate it, however, it has happened more than once in about 10 minutes.

**Comment by LogicalLion** [comment]
Also, I have this error too quite often. It wouldn't be super much of an issue other than it is often and crashes my studio.
![image](https://github.com/CelnakRBLX/SmartBone-2/assets/161987255/12f77139-4de5-4a51-acce-df9c314046e1)

**Comment by JakeyWasTaken** [comment]
The 2nd error is because you dont have a terrain object in workspace, which is needed for the gizmos.

**Comment by LogicalLion** [comment]
Am I able to add a little bit of terrain and have the issue be fixed? I am not using the actual terrain for my game.

**Comment by LogicalLion** [comment]
![image](https://github.com/CelnakRBLX/SmartBone-2/assets/161987255/64e3be0a-c2a8-4dd7-b548-324b5785538f)
Such as this? If so it has already been under it. Sorry for all the bothersome questions too.

**Comment by JakeyWasTaken** [comment]
Are you sure some of your code isn't deleting it at runtime?

**Comment by JakeyWasTaken** [comment]
I believe this issue may be fixed in https://github.com/CelnakRBLX/SmartBone-2/pull/23, next version might fix this for you.

**Comment by JakeyWasTaken** [comment]
Please inform me if your still receiving this error as of the latest version (0.3.1)

**Comment by JakeyWasTaken** [comment]
I'm gonna close this as fixed, if you still experience this I'll reopen this issue.
